version: '2.0'
services:
    mysql:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=bugtracker
            - MYSQL_USER=mantisbt
            - MYSQL_PASSWORD=mantisbt
        restart: always
        networks:
            - mantisbt

    mantisbt:
        image: mantisbt:latest
        ports:
            - "8080:80"
        links:
            - mysql
        volumes:
            - ./config:/config
        restart: always
        networks:
            - mantisbt


networks:
    mantisbt: